### ISSUE TITLE
Load this module in HTML document doesn't work

### ISSUE THREAD

**Issue by garryyao** [PredixDev/px-dark-theme#2]
Sorry but no idea how to get this working - Bower installing this component gives us a bare style module which does not impact document scope: Polymer document x-scope styling requires styles block to be wrapped in  `<style is="custom-style">` instead?

**Comment by mdwragg** [comment]
Here is an example of how to use it:

http://codepen.io/mdwragg/pen/qRKzGN?editors=1000#0

You'll note that instead of loading 'px-theme' we're now loading and referencing 'px-dark-theme'. We're working on documenting all our theming work, both as a consumer of dark theme and how to customise themes to your requirement.

Thanks.

**Comment by garryyao** [comment]
This is really cool, thanks!
<img width="1440" alt="screen shot 2017-02-13 at 5 32 42 pm" src="https://cloud.githubusercontent.com/assets/56495/22877898/7cbdefb6-f212-11e6-8e05-d0cebb152498.png">

**Comment by mdwragg** [comment]
Cool! Looking good :-)
